### ISSUE TITLE
How to trim the blank lines with <%= %> expressions

### ISSUE THREAD

**Issue by beviz** [ruby/erb#24] opened 2022-11-02 11:23 UTC
ERB supports to use `trim_mode: '-'` to trim the blank lines, including `<%-` to trim the previous line and `-%>` to trim the following.

Now I have a scenario to output one line in a yaml file. I want to shorten the following multiple lines 

```YAMl
repos:
  - repo: https://github.com/repo1
    hooks:
      - hook_1
      <%- if condition -%>
      - hook2
      <%- end -%>
      <%- if condition -%>
      - hook3
      <%- end -%>
```

to 

```YAML
repos:
  - repo: https://github.com/repo1
    hooks:
      - hook_1
      <%-= '- hook2' if condition -%>
      <%-= '- hook3' if condition -%>
```

But ERB doesn't yet support such a `<%-=` corresponding to `<%-`.

Team, can you please add this feature? It would become more consistent and convenient.

**Comment by k0kubun** [comment] 2022-11-02 16:48
Implementation-wise, what matters for `trim_mode: '-'` is only the closing bracket, `-%>`. `<%= -%>` seems to be working as intended.

```rb
irb(main)[10:0]> puts ERB.new("a\n<%= '' %>\nc", trim_mode: '-').result
a

c
=> nil
irb(main)[11:0]> puts ERB.new("a\n<%= '' -%>\nc", trim_mode: '-').result
a
c
=> nil
```

**Comment by beviz** [comment] 2022-11-02 17:35
@k0kubun you said the '-' is only the closing bracket, but in fact it also supports the opening bracket.

![image](https://user-images.githubusercontent.com/1106312/199560710-4290a63f-3894-4c05-a459-135cbf7bd572.png)

If it only supports `<%-` and not `<%-=`, it's incomplete.

**Comment by k0kubun** [comment] 2022-11-02 17:59
> you said the '-' is only the closing bracket

I didn't :) I just said `-%>` matters and whether you use `<%` or `<%-` doesn't matter.

I'm not the person who introduced this incompleteness. If you don't like the inconsistency, you can simply stop using `<%-`. I don't think it's worth introducing `<%-=` that behaves exactly the same as `<%=`.

**Comment by beviz** [comment] 2022-11-09 16:27
@k0kubun 

> I don't think it's worth introducing <%-= that behaves exactly the same as <%=.

I think you didn't get my point. Of course their behaviors aren't the same. Don't you know the `<%-` symbol trims the blank line before itself? I pointed it out multiple times in the above two screenshots. Would you please read them again carefully  and reconsider my request?

**Comment by k0kubun** [comment] 2022-11-09 17:34
My bad. Yes, you're right. I was reading my own document on how trim_mode behaves and it didn't mention `<%-`, but the code does seem to have special handling of `<%-`. 

Can you explain the use case though? The current issue description explains what feature is missing, but it doesn't really communicate why it's needed. A real-ish template example you're currently using (a workaround to remove the whitespace, maybe like no indentation before `<%=`?) and how it could be better with the presence of the feature would be nice. Also please don't use a screen shot and just use a code block so that maintainers can just copy and test the exact same template.

**Comment by beviz** [comment] 2022-11-13 08:46
@k0kubun updated, please take a look if it's good enough now.

**Comment by k0kubun** [comment] 2022-11-14 05:34
Nice :+1: Thank you.

**Comment by k0kubun** [comment] 2022-11-14 05:37
This proposal makes sense. Would you be interested in writing a patch?

**Comment by beviz** [comment] 2022-11-15 14:49
@k0kubun okay then, I can have a try this weekend.

**Comment by beviz** [comment] 2022-11-19 12:53
@k0kubun see https://github.com/ruby/erb/pull/31

**Comment by k0kubun** [comment] 2022-11-28 19:32
As discussed in https://github.com/ruby/erb/pull/31#discussion_r1033967266, I moved this project to https://github.com/k0kubun/erb-trim. Let's maintain it there until we come up with an idea to make it as efficient as `-%>`.

**Closed by k0kubun** 2022-11-28 19:32 UTC
